spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/customerDB
    username: admin
    password: 123
    driver-class-name: org.postgresql
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgres